import { expect, test } from '@playwright/test'

test('streams a non-approvable draft, resumes feedback, cancels safely and resets its conversation', async ({ page }) => {
  await page.setViewportSize({ width: 1180, height: 760 })
  await page.goto('/?workspace=empty&planning=slow')
  await page.getByRole('button', { name: '실제 Git 프로젝트 추가' }).last().click()
  await page.getByRole('button', { name: '첫 작업 만들기' }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('작업 제목').fill('내 위치 버튼 구현')
  await dialog.getByLabel('목표와 완료 조건').fill('내 위치로 이동하는 버튼과 권한 거부 안내를 구현해 주세요.')
  await dialog.getByLabel('구현 전 테크스펙 만들기').check()
  await dialog.getByRole('button', { name: '테크스펙 만들기', exact: true }).click()
  const progress = dialog.getByRole('region', { name: '테크스펙 생성 진행 상황' })
  await expect(progress).toContainText('새 계획 대화')
  await expect(progress).toContainText('조사 도구 호출')
  await expect(progress).toContainText('조사 45초 또는 도구 호출 8회')
  const panel = await progress.boundingBox()
  const cancel = await dialog.getByRole('button', { name: '생성 취소', exact: true }).boundingBox()
  expect(panel).not.toBeNull()
  expect(cancel).not.toBeNull()
  expect(cancel!.x).toBeGreaterThan(panel!.x)
  expect(cancel!.x + cancel!.width).toBeLessThanOrEqual(panel!.x + panel!.width)
  await expect(progress.locator('pre')).toContainText('내 위치로 이동')
  await expect(dialog.getByRole('button', { name: '검증 계획 확인하고 작업 등록' })).toBeDisabled()
  await expect(dialog.getByText('테크스펙 revision 1')).toBeVisible()
  const edited = (await dialog.getByLabel('테크스펙 본문').inputValue()) + '\n\n직접 편집한 예외 처리'
  await dialog.getByLabel('테크스펙 본문').fill(edited)
  await dialog.getByLabel('테크스펙 개선 의견').fill('권한 거부 이후 복구 방법도 추가해줘')
  await dialog.getByRole('button', { name: '피드백 반영', exact: true }).click()
  await expect(progress).toContainText('이전 대화 이어서 진행')
  await dialog.getByRole('button', { name: '생성 취소', exact: true }).click()
  await expect(progress).toContainText('생성을 취소했습니다')
  await expect(dialog.getByLabel('테크스펙 본문')).toHaveValue(edited)
  await expect(dialog.getByLabel('테크스펙 개선 의견')).toHaveValue('권한 거부 이후 복구 방법도 추가해줘')
  await expect(dialog.getByText('테크스펙 revision 1')).toBeVisible()
  await dialog.getByRole('button', { name: '새 대화로 시작' }).click()
  await expect(dialog.getByLabel('테크스펙 본문')).toHaveValue(edited)
  await dialog.getByRole('button', { name: '피드백 반영', exact: true }).click()
  await expect(progress).toContainText('새 계획 대화')
  await expect(dialog.getByText('테크스펙 revision 2')).toBeVisible()
  await expect(dialog.getByLabel('테크스펙 본문')).toHaveValue(/직접 편집한 예외 처리/)
})

test('closing a generating draft does not apply its late response to a new task form', async ({ page }) => {
  await page.goto('/?workspace=empty&planning=slow')
  await page.getByRole('button', { name: '실제 Git 프로젝트 추가' }).last().click()
  await page.getByRole('button', { name: '첫 작업 만들기' }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('작업 제목').fill('이전 초안')
  await dialog.getByLabel('목표와 완료 조건').fill('다른 화면으로 전파되면 안 되는 계획입니다.')
  await dialog.getByLabel('구현 전 테크스펙 만들기').check()
  await dialog.getByRole('button', { name: '테크스펙 만들기', exact: true }).click()
  await expect(dialog.getByRole('button', { name: '생성 취소', exact: true })).toBeVisible()
  await dialog.getByRole('button', { name: '닫기', exact: true }).click()
  await page.getByRole('button', { name: '첫 작업 만들기' }).click()
  await dialog.getByLabel('작업 제목').fill('새 초안')
  await dialog.getByLabel('목표와 완료 조건').fill('새 대화에서만 만드는 독립된 계획입니다.')
  await dialog.getByLabel('구현 전 테크스펙 만들기').check()
  await expect(dialog.getByRole('region', { name: '테크스펙 생성 진행 상황' })).toHaveCount(0)
  await dialog.getByRole('button', { name: '테크스펙 만들기', exact: true }).click()
  await expect(dialog.getByRole('region', { name: '테크스펙 생성 진행 상황' })).toContainText('새 계획 대화')
  await expect(dialog.getByText('테크스펙 revision 1')).toBeVisible()
  await expect(dialog.getByLabel('테크스펙 본문')).toHaveValue(/새 대화에서만 만드는/)
  await expect(dialog.getByLabel('테크스펙 본문')).not.toHaveValue(/다른 화면으로 전파/)
})
